// Must exactly match `site_blocks_icon_key_check` in
// ostati-app/supabase/migrations/0074_site_blocks.sql.
export const ICON_KEYS = [
  'Wrench',
  'Zap',
  'Paintbrush',
  'Snowflake',
  'Flame',
  'Armchair',
  'PlugZap',
  'Grid2X2',
  'PanelsTopLeft',
  'DoorOpen',
  'LockKeyhole',
  'Hammer',
  'House',
  'Sparkles',
  'Package',
  'ShieldCheck',
  'MessageCircle',
  'Tags',
  'ScanSearch',
  'FileText',
  'ThumbsUp',
  'Star',
  'CheckCircle',
  'Users',
  'Clock',
] as const;
